biome.category.100=minecraft:nether_wastes
biome.category.101=minecraft:soul_sand_valley
biome.category.102=minecraft:crimson_forest
biome.category.103=minecraft:warped_forest
biome.category.104=minecraft:basalt_deltas