sliders=SHADOW_BIAS SHADOW_DISTORT_FACTOR SHADOW_BRIGHTNESS shadowMapResolution

uniform.int.biome_precipitation = biome_precipitation
texture.composite.colortex2.format=R16F
texture.composite.colortex3.format=RGBA8
texture.gbuffers.colortex1.format=RGBA8