sliders=SHADOW_BIAS SHADOW_DISTORT_FACTOR SHADOW_BRIGHTNESS shadowMapResolution CLOUD_COVERAGE CLOUD_SOFTNESS CLOUD_SPEED CONSTELLATION_SEED CONSTELLATION_COUNT GALAXY_AZIMUTH_ROTATE WETNESS_DARKEN WETNESS_SKY_STRENGTH PUDDLE_SCALE PUDDLE_RIPPLE_STRENGTH

screen = NORMAL_BIAS [SHADOW] [CLOUDS] [NIGHT_SKY] [WETNESS]

screen.SHADOW.columns = 2
screen.SHADOW = SHADOWS COLORED_SHADOWS EXCLUDE_FOLIAGE SHADOW_BRIGHTNESS SHADOW_BIAS SHADOW_DISTORT_ENABLED SHADOW_DISTORT_FACTOR shadowMapResolution

screen.CLOUDS.columns = 1
screen.CLOUDS = CLOUD_COVERAGE CLOUD_SOFTNESS CLOUD_SPEED

screen.NIGHT_SKY.columns = 1
screen.NIGHT_SKY = CONSTELLATION_SEED CONSTELLATION_COUNT GALAXY_AZIMUTH_ROTATE

screen.WETNESS.columns = 2
screen.WETNESS = ENABLE_WETNESS WETNESS_DARKEN WETNESS_SKY_STRENGTH PUDDLE_SCALE PUDDLE_RIPPLE_STRENGTH

uniform.int.biome_precipitation = biome_precipitation
uniform.int.biome_category = biome_category
texture.composite.colortex2.format=R16F
texture.composite.colortex3.format=RGBA8
texture.gbuffers.colortex1.format=RGBA8

uniform.float.customWetness = smooth(clamp((rainStrength - 0.05) / 0.50, 0.0, 1.0), 8, 5)
clouds=off