sliders=SHADOW_BIAS SHADOW_DISTORT_FACTOR SHADOW_BRIGHTNESS shadowMapResolution

screen = NORMAL_BIAS [SHADOW]

screen.SHADOW.columns = 2
screen.SHADOW = SHADOWS COLORED_SHADOWS EXCLUDE_FOLIAGE SHADOW_BRIGHTNESS SHADOW_BIAS SHADOW_DISTORT_ENABLED SHADOW_DISTORT_FACTOR shadowMapResolution

uniform.int.biome_precipitation = biome_precipitation
texture.composite.colortex2.format=R16F
texture.composite.colortex3.format=RGBA8
texture.gbuffers.colortex1.format=RGBA8